# Generated by Django 6.0.6 on 2026-07-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
