# Generated by Django 6.0.6 on 2026-07-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_teammemberinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUPERVISOR_ASSIGNED', 'Supervisor Assigned'), ('REVISION_REQUIRED', 'Revision Required'), ('PROPOSAL_APPROVED', 'Proposal Approved'), ('IN_PROGRESS', 'In Progress'), ('PROGRESS_REVIEW', 'Progress Under Review'), ('FINAL_SUBMITTED', 'Final Submitted'), ('READY_FOR_VIVA', 'Ready For Viva'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
