# Generated by Django 6.0.6 on 2026-08-01 09:46

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdocument',
            options={'ordering': ['-uploaded_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='projectfeedback',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='teammemberinfo',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='document_type',
            field=models.CharField(choices=[('PROPOSAL', 'Proposal'), ('PROGRESS_REPORT', 'Progress Report'), ('PRESENTATION', 'Presentation'), ('FINAL_REPORT', 'Final Report'), ('SOURCE_CODE', 'Source Code'), ('RESEARCH_PAPER', 'Research Paper'), ('DIAGRAM', 'Diagram or Image'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_project_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REVISION_REQUIRED', 'Revision Required'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='supervisor_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUPERVISOR_ASSIGNED', 'Supervisor Assigned'), ('REVISION_REQUIRED', 'Revision Required'), ('PROPOSAL_APPROVED', 'Proposal Approved'), ('IN_PROGRESS', 'In Progress'), ('PROGRESS_REVIEW', 'Progress Under Review'), ('FINAL_SUBMITTED', 'Final Submitted'), ('READY_FOR_VIVA', 'Ready For Viva'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(upload_to='project_documents/%Y/%m/', validators=[projects.models.validate_project_document]),
        ),
    ]
