# Generated by Django 6.0.6 on 2026-08-01 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectdocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='is_latest',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='projects.projectdocument'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='submission_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='document_type',
            field=models.CharField(choices=[('PROPOSAL', 'Proposal'), ('PROPOSAL_PRESENTATION', 'Proposal Presentation'), ('PROGRESS_REPORT', 'Progress Report'), ('FINAL_REPORT', 'Final Report'), ('FINAL_PRESENTATION', 'Final Presentation'), ('THESIS_BOOK', 'Thesis Book'), ('RESEARCH_PAPER', 'Research Paper'), ('DATASET', 'Dataset'), ('SOURCE_CODE', 'Source Code'), ('POSTER', 'Poster'), ('DIAGRAM', 'Diagram or Image'), ('OTHER', 'Other')], default='OTHER', max_length=40),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['project', 'document_type', 'is_latest'], name='project_doc_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['submission_group', 'version'], name='project_doc_version_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectdocument',
            constraint=models.UniqueConstraint(fields=('submission_group', 'version'), name='unique_submission_version'),
        ),
    ]
