# Generated by Django 6.0.6 on 2026-08-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='project_duration',
            field=models.PositiveSmallIntegerField(default=3, help_text='Total number of semesters for the project or thesis.'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='project_start_term',
            field=models.CharField(blank=True, choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='project_start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
