# Generated by Django 6.0.6 on 2026-08-01 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='industrialtraining',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='trainingfeedback',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='industrialtraining',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industrialtraining',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SUPER_ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='industrialtraining',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industrialtraining',
            name='designation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='industrialtraining',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='industrial_training_offer_letters/'),
        ),
        migrations.AddField(
            model_name='industrialtraining',
            name='status_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='industrialtraining',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='industrialtraining',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='training.company'),
        ),
        migrations.AlterField(
            model_name='industrialtraining',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingfeedback',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'SUPERVISOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='training_feedback_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TrainingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_status_changes', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='training.industrialtraining')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
